// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubfrontLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubfrontRight;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubrearLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveBaseSubrearRight;
std::shared_ptr<frc::RobotDrive> RobotMap::driveBaseSubarcDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveBaseSubfrontLeft.reset(new WPI_TalonSRX(0));
    
    
    driveBaseSubfrontRight.reset(new WPI_TalonSRX(1));
    
    
    driveBaseSubrearLeft.reset(new WPI_TalonSRX(2));
    
    
    driveBaseSubrearRight.reset(new WPI_TalonSRX(3));
    
    
    driveBaseSubarcDrive.reset(new frc::RobotDrive(driveBaseSubfrontLeft, driveBaseSubrearLeft,
              driveBaseSubfrontRight, driveBaseSubrearRight));
    
    driveBaseSubarcDrive->SetSafetyEnabled(true);
        driveBaseSubarcDrive->SetExpiration(0.1);
        driveBaseSubarcDrive->SetSensitivity(0.5);
        driveBaseSubarcDrive->SetMaxOutput(1.0);
        driveBaseSubarcDrive->SetInvertedMotor(frc::RobotDrive::kFrontLeftMotor, true);
        driveBaseSubarcDrive->SetInvertedMotor(frc::RobotDrive::kRearLeftMotor, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
