// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutonomousCommand::AutonomousCommand(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveBaseSub.get());
	Speed = 0;
	Turn = 0;
	autoFinished = false;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {
	Speed = 0;
	Turn = 0;
	autoFinished = false;

}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	//frc::Wait(1.0); //1 Second
	static int timer = 0;
	Speed = -0.2;
	Turn = 0;

	Robot::driveBaseSub->arcadeDrive(Speed,Turn);
	timer++;


	if (timer > 250){
		autoFinished = true;
	}



}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	if (autoFinished){
		return true;
	}
	else {
    return false;
	}

}

// Called once after isFinished returns true
void AutonomousCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {

}
