// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "jawzOpen.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

jawzOpen::jawzOpen(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	lSpeed = 0;
	rSpeed = 0;
	button1Pressed = false;
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void jawzOpen::Initialize() {
	lSpeed = 0;
	rSpeed = 0;
	button1Pressed = false;

}

// Called repeatedly when this Command is scheduled to run
void jawzOpen::Execute() {
	button1Pressed = Robot::oi->getController()->GetRawButton(1);

			if (button1Pressed) {
				lSpeed = -0.5;
				rSpeed = 0.5;
				Robot::intake->JawzOpen(lSpeed, rSpeed);
			}

			else {
				lSpeed = 0;
				rSpeed = 0;
				Robot::intake->JawzOpen(lSpeed, rSpeed);
			}
}

// Make this return true when this Command no longer needs to run execute()
bool jawzOpen::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void jawzOpen::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void jawzOpen::Interrupted() {

}
