// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Intake.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Intake::Intake() : frc::Subsystem("Intake") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftClaw = RobotMap::intakeleftClaw;
    rightClaw = RobotMap::intakerightClaw;
    leftIntake = RobotMap::intakeleftIntake;
    rightIntake = RobotMap::intakerightIntake;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Intake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Intake::Periodic() {
    // Put code here to be run every loop

}

void Intake::JawzOpen(double lSpeed, double rSpeed){
	leftClaw->Set(lSpeed);
	rightClaw->Set(rSpeed);

}

void Intake::JawzClose(double lSpeed, double rSpeed){
	leftClaw->Set(lSpeed);
	rightClaw->Set(rSpeed);

}

void Intake::IntakeIn(double lSpeed, double rSpeed){
	leftIntake->Set(lSpeed);
	rightIntake->Set(rSpeed);
}

void Intake::IntakeOut(double lSpeed, double rSpeed){
	leftIntake->Set(lSpeed);
	rightIntake->Set(rSpeed);

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

