// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "liftUp.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

liftUp::liftUp(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lift.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	button8Pressed = false;
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void liftUp::Initialize() {
	button8Pressed = false;
}

// Called repeatedly when this Command is scheduled to run
void liftUp::Execute() {

	Robot::lift->LiftUp();


}

// Make this return true when this Command no longer needs to run execute()
bool liftUp::IsFinished() {
	button8Pressed = Robot::oi->getController()->GetRawButton(8);
		if (button8Pressed == false){
			return true;
		}
		else{
	    return false;
		}
}

// Called once after isFinished returns true
void liftUp::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void liftUp::Interrupted() {

}
