/*
 * zeroYaw.cpp
 *
 *  Created on: Mar 13, 2018
 *      Author: owner
 */


#include "zeroYaw.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

zeroYaw::zeroYaw(): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveBaseSub.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	button9Pressed = false;
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void zeroYaw::Initialize() {
	button9Pressed = false;

}

// Called repeatedly when this Command is scheduled to run
void zeroYaw::Execute() {

	button9Pressed = Robot::oi->getController()->GetRawButton(9);
		if (button9Pressed) {
		//Zeros gyroscope based on current position
		Robot::driveBaseSub->ResetGyro();
		}
		else {

		}
}

// Make this return true when this Command no longer needs to run execute()
bool zeroYaw::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void zeroYaw::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void zeroYaw::Interrupted() {

}


