/*
 * Zero Yaw.h
 *
 *  Created on: Mar 12, 2018
 *      Author: owner
 */

#ifndef SRC_COMMANDS_ZEROYAW_H_
#define SRC_COMMANDS_ZEROYAW_H_

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class zeroYaw: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	zeroYaw();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	bool button9Pressed;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};


#endif /* SRC_COMMANDS_ZEROYAW_H_ */
