// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"
#include "AHRS.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<WPI_TalonSRX> driveBaseSubfrontLeft;
	static std::shared_ptr<WPI_TalonSRX> driveBaseSubrearLeft;
	static std::shared_ptr<WPI_TalonSRX> driveBaseSubfrontRight;
	static std::shared_ptr<WPI_TalonSRX> driveBaseSubrearRight;
	static std::shared_ptr<AHRS> driveBaseSubgyro;
	static std::shared_ptr<MecanumDrive> driveBaseSubm_drive;
	static std::shared_ptr<frc::Compressor> liftCompressor;
	static std::shared_ptr<frc::DoubleSolenoid> liftsLift;
	static std::shared_ptr<frc::SpeedController> intakeleftClaw;
	static std::shared_ptr<frc::SpeedController> intakerightClaw;
	static std::shared_ptr<frc::SpeedController> intakeleftIntake;
	static std::shared_ptr<frc::SpeedController> intakerightIntake;
	static std::shared_ptr<frc::AnalogPotentiometer> elevatorelevatorPot;
	static std::shared_ptr<frc::SpeedController> elevatorelevatorDrive;
	static std::shared_ptr<frc::DoubleSolenoid> tiltsTilt;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
